{
 "title": "Video Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Video Sender", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 1, "y": 1 },
   "targets": [
    { "expr": "pc_video_tx_bytes_sent" }
   ]
  },
  {
   "title": "NACK count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 1 },
   "targets": [
    { "expr": "pc_video_tx_nack_count" }
   ]
  },
  { "title": "Video Receiver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Keyframes Decoded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 1, "y": 9 },
   "targets": [
    { "expr": "pc_video_rx_keyframes_decoded" }
   ]
  },
  {
   "title": "Remote jitter",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 9 },
   "targets": [
    { "expr": "pc_video_tx_remote_jitter" }
   ]
  },
  {
   "title": "Video Bytes Received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 1, "y": 16 },
   "targets": [
    { "expr": "pc_video_rx_bytes_received" }
   ]
  },
  {
   "title": "Video Packets Received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 16 },
   "targets": [
    { "expr": "pc_video_rx_packets_received" }
   ]
  }
 ]
}